name: 'main'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: 1 }
          - { name: 2 }
          - { name: 3 }
          - { name: 4 }
          - { name: 5 }
          - { name: 6 }
    steps:
      - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2
        with:
          msystem: ucrt64
          install: mingw-w64-ucrt-x86_64-cc
          release: false
  
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - run: |
          # Set SetErrorMode(SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX)
          Add-Type -TypeDefinition @"
          using System;
          using System.Runtime.InteropServices;
          public class ErrorModeHelper
          {
              [DllImport("kernel32.dll")]
              public static extern uint SetErrorMode(uint uMode);
          }
          "@
          $ErrorMode = 0x0001 -bor 0x0002 # SEM_FAILCRITICALERRORS | SEM_NOGPFAULTERRORBOX
          [ErrorModeHelper]::SetErrorMode($ErrorMode)

          # Install meson, ninja and add GCC to PATH
          pip install meson
          pip install ninja
          $env:PATH="C:\msys64\ucrt64\bin;$env:PATH"

          # See where things are comming from
          (Get-Command meson).Path
          (Get-Command ninja).Path
          (Get-Command gcc).Path
          (Get-Command python).Path

          # Build the meson project
          cd project
          meson setup _build
          cd _build
          ninja
