name: 'main'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{matrix.runson}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2019 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2019 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2019 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2019 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2022 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2022 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2022 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2022 }
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: >-
            mingw-w64-${{matrix.env}}-ninja
            mingw-w64-${{matrix.env}}-cc
            git

      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: '3.10.0-alpha.1'

      - uses: actions/checkout@v3

      - shell: msys2 {0}
        run: |
          ./test.sh '${{ steps.setup-python.outputs.python-path }}'
