name: 'main'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{matrix.runson}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2019 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2019 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2019 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2019 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2019 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2019 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2019 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2022 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2022 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2022 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2022 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2022 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2022 }
          - { sys: ucrt64, env: ucrt-x86_64, runson: windows-2022 }
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          install: >-
            mingw-w64-${{matrix.env}}-ninja
            mingw-w64-${{matrix.env}}-cc
            git

      - uses: actions/checkout@v3

      - run: |
          cd D:\
          git clone https://github.com/python/cpython.git
          cd cpython
          git checkout bc87ac6d0b13116f525215f8a31b46506bc8d629
          .\PCbuild\build.bat -e
          .\PCbuild\amd64\python.exe --version

      - shell: msys2 {0}
        run: |
          ./test.sh '/D/cpython/PCbuild/amd64/python.exe'
